### ISSUE TITLE
Incorrect display of paameters in logic app if TriggerInput<TOutput> is used in push triggers

### ISSUE THREAD

**Issue by AndyEdmonds** [nihaue/TRex#4]
In defining an app that has only a push trigger configured, that takes no parameters, and using TRex, the Logic App display does not show the detail of the parameters. If, instead I define a dummy class and use the TriggerInput<TInput,TOutput> with the dummy class as the input, the output parameters are correctly displayed. So:
       [Trigger(TriggerType.Push, typeof(PushEvent))]
        [Metadata("Form completion")]
        [HttpPut]
        [Route("{triggerId}")]
        public HttpResponseMessage CompletedFormPushTrigger(string triggerId, [FromBody]TriggerInput<Dummy, PushEvent> parameters)
        {
            CallbackStore[triggerId] = new StoredCallBack()
            {
                CallbackUri = parameters.GetCallback().CallbackUri
            };
            telemetry.TrackEvent(string.Format("Push Trigger registered {0}", triggerId)); 
            // Notify the Logic App that the callback was registered
            return Request.PushTriggerRegistered(parameters.GetCallback());
        }
Displays properly the parameters inside PushEvent. Leaving out the Dummy class results in no parameters displayed.

**Comment by nihaue** [comment]
I'll check into this tonight (Pacific Time Zone) to see where the issue lives (i.e., whether it's something in T-Rex / Swashbuckle / or the Logic App designer), and then determine how to tackle it from there.

**Comment by nihaue** [comment]
I got it backwards in the docs with the last update. The class is actually **`TriggerInput<TInput>`** (emphasis on **TInput** rather than **TOutput**). So essentially it looks like that sets up the trigger to not have a strongly typed response, but doesn't deal with the inputs being empty. I think this may be a case where a dummy class is required.

I would recommend posing the question on the MSDN social forums asking about the null input / typed output scenario to see how that would be handled in the metadata, then file an issue again whenever you get an answer about what that scenario should look like, and I'll make updates accordingly.
