### ISSUE TITLE
Assembly does not have a strong name

### ISSUE THREAD

**Issue by cmshawns** [nihaue/TRex#7]
```
Error CS8002: Referenced assembly 'TRex.Metadata, Version=0.1.8.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.
```
All our assemblies have strong names, which in turn requires that all libraries have strong names. I know I can compile TRex myself with a strong name, and I'm willing to do so, but am wondering if you'd be willing to distribute it with a strong name.

Thanks :-)

**Comment by nihaue** [comment]
I'll do that in the pre-release "powerapps" branch. I did some tests today to determine the feasibility and impact (given use of a bunch of other libraries, and use of friend assemblies).

It looks like it's possible against that branch for sure after all projects are signed and the public key is added to the friend assembly declarations in the TRex.Metadata.Attributes project.

I have a release planned for next week, so it's likely to incorporate that change.

**Comment by cmshawns** [comment]
Thanks @nihaue :-)

**Comment by nihaue** [comment]
This is resolved in v2.0.1-alpha ([available on nuget](https://www.nuget.org/packages/TRex/2.0.1-alpha)). You can see [sample usage here](https://github.com/nihaue/TRex/tree/powerapps/Source/QuickLearn.SampleApi/Controllers).

**Comment by cmshawns** [comment]
@nihaue Do you have any kind of roadmap for when the powerapps branch will be released (i.e. stable)? I'm trying it out now as we definitely need the dynamic extensions, but need to ease management's minds about using an alpha. Thanks for the great work :-)

**Comment by nihaue** [comment]
Once the features hit the Logic App designer (instead of just Microsoft Flow) I will be removing "alpha" from the version number. It is unlikely that the code itself will change at that time, unless there is some sort of breaking change in the designer that requires it.

Watch [this blog](https://blogs.msdn.microsoft.com/logicappsupdate/), and if you see something about designer support for dynamic swagger in custom actions before I do -- ping me. That's what I'm watching as my signal for release.
